name: Build
on:
  push:
    branches:
      - '**'
    
concurrency:
  group: build-${{ github.ref || github.run_id }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable  
        if: matrix.os == 'macos-latest'                    
      - name: "Run script"
        run: |
          ./ci/build.sh
        shell: bash
